spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=VsotegYRYxfBOHDPcykkPhYWAtWjxNEg
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
otx.api.key=5890f142c56afff43abb2524c2d01285abbd62cfeb92f9f93b855baf4a3c68e7